export const categories = {
    "Fruits": [
        { word: "apple", hint: "" },
        { word: "banana", hint: "" },
        { word: "cherry", hint: "" },
        { word: "date", hint: "" },
        { word: "elderberry", hint: "A berry from a small, dark shrub" },
        { word: "fig", hint: "" },
        { word: "grape", hint: "" },
        { word: "honeydew", hint: "A type of melon" },
        { word: "kiwi", hint: "" },
        { word: "lemon", hint: "" },
        { word: "lime", hint: "" },
        { word: "mango", hint: "" },
        { word: "nectarine", hint: "" },
        { word: "orange", hint: "" },
        { word: "papaya", hint: "" },
        { word: "quince", hint: "A fruit used in making jellies" },
        { word: "raspberry", hint: "" },
        { word: "strawberry", hint: "" },
        { word: "tangerine", hint: "" },
        { word: "watermelon", hint: "" },
        { word: "xigua", hint: "Another name for watermelon" },
        { word: "yuzu", hint: "A citrus fruit from East Asia" },
        { word: "zucchini", hint: "" },
        { word: "plum", hint: "" },
        { word: "peach", hint: "" },
        { word: "pear", hint: "" },
        { word: "apricot", hint: "" },
        { word: "blackberry", hint: "" },
        { word: "blueberry", hint: "" },
        { word: "cranberry", hint: "" },
        { word: "dragonfruit", hint: "A tropical fruit with scaly skin" },
        { word: "gooseberry", hint: "" },
        { word: "grapefruit", hint: "" },
        { word: "guava", hint: "" },
        { word: "jackfruit", hint: "A large tropical fruit with spiky skin" },
        { word: "lychee", hint: "A small fruit with rough skin and sweet flesh" },
        { word: "mandarin", hint: "" },
        { word: "mulberry", hint: "" },
        { word: "olive", hint: "" },
        { word: "passionfruit", hint: "" },
        { word: "persimmon", hint: "An orange fruit that looks like a tomato" },
        { word: "pineapple", hint: "" },
        { word: "pomegranate", hint: "" },
        { word: "starfruit", hint: "A fruit with a star-shaped cross-section" },
        { word: "tamarind", hint: "A tropical fruit with a tangy taste" },
        { word: "tomato", hint: "" },
        { word: "cloudberry", hint: "" },
        { word: "camu camu", hint: "A berry from the Amazon rainforest" },
        { word: "cantaloupe", hint: "" }
    ],
    "Animals": [
        { word: "cat", hint: "" },
        { word: "dog", hint: "" },
        { word: "elephant", hint: "" },
        { word: "giraffe", hint: "" },
        { word: "hippopotamus", hint: "A large, mostly herbivorous mammal" },
        { word: "iguana", hint: "" },
        { word: "jaguar", hint: "" },
        { word: "kangaroo", hint: "" },
        { word: "lemur", hint: "" },
        { word: "mongoose", hint: "" },
        { word: "antelope", hint: "" },
        { word: "bear", hint: "" },
        { word: "cheetah", hint: "" },
        { word: "dolphin", hint: "" },
        { word: "eagle", hint: "" },
        { word: "fox", hint: "" },
        { word: "goat", hint: "" },
        { word: "hedgehog", hint: "" },
        { word: "impala", hint: "" },
        { word: "jellyfish", hint: "" },
        { word: "koala", hint: "" },
        { word: "lion", hint: "" },
        { word: "monkey", hint: "" },
        { word: "narwhal", hint: "A whale with a long, spiraled tusk" },
        { word: "octopus", hint: "" },
        { word: "penguin", hint: "" },
        { word: "quokka", hint: "A small wallaby native to Australia" },
        { word: "rhinoceros", hint: "" },
        { word: "shark", hint: "" },
        { word: "tiger", hint: "" },
        { word: "urial", hint: "A type of wild sheep" },
        { word: "vulture", hint: "" },
        { word: "wolf", hint: "" },
        { word: "xenopus", hint: "A genus of aquatic frogs" },
        { word: "yak", hint: "" },
        { word: "zebra", hint: "" },
        { word: "alligator", hint: "" },
        { word: "bat", hint: "" },
        { word: "camel", hint: "" },
        { word: "duck", hint: "" },
        { word: "falcon", hint: "" },
        { word: "gorilla", hint: "" },
        { word: "hawk", hint: "" },
        { word: "ibex", hint: "" },
        { word: "jackal", hint: "" },
        { word: "kiwi", hint: "A flightless bird native to New Zealand" },
        { word: "lemur", hint: "" },
        { word: "manatee", hint: "" },
        { word: "newt", hint: "" },
        { word: "orca", hint: "" },
        { word: "panda", hint: "" },
        { word: "quail", hint: "" },
        { word: "reindeer", hint: "" },
        { word: "seal", hint: "" },
        { word: "tapir", hint: "A large herbivorous mammal with a short trunk" },
        { word: "urchin", hint: "A small, spiny sea creature" },
        { word: "vole", hint: "" },
        { word: "wombat", hint: "" },
        { word: "xerus", hint: "A genus of African ground squirrels" },
        { word: "yak", hint: "" },
        { word: "zebu", hint: "" },
        { word: "aardvark", hint: "" },
        { word: "badger", hint: "" },
        { word: "capybara", hint: "" },
        { word: "deer", hint: "" },
        { word: "emu", hint: "" },
        { word: "ferret", hint: "" },
        { word: "gecko", hint: "" },
        { word: "heron", hint: "" },
        { word: "ibis", hint: "" },
        { word: "jaguarundi", hint: "A small, wild cat native to Central and South America" },
        { word: "kudu", hint: "A type of antelope with spiral horns" },
        { word: "lemur", hint: "" },
        { word: "moose", hint: "" },
        { word: "nighthawk", hint: "A nocturnal bird" },
        { word: "ostrich", hint: "" },
        { word: "platypus", hint: "" },
        { word: "quetzal", hint: "A colorful bird native to Central America" },
        { word: "skunk", hint: "" },
        { word: "tamarin", hint: "" },
        { word: "uakari", hint: "A small primate with a red face" },
        { word: "vicuna", hint: "A wild relative of the llama" },
        { word: "walrus", hint: "" },
        { word: "xoloitzcuintli", hint: "A Mexican hairless dog breed" },
        { word: "yak", hint: "" },
        { word: "zorilla", hint: "A small carnivorous mammal, similar to a skunk" },
        { word: "anaconda", hint: "" },
        { word: "bison", hint: "" },
        { word: "chinchilla", hint: "" },
        { word: "dugong", hint: "" }
    ],
    "Countries": [
        { word: "argentina", hint: "" },
        { word: "brazil", hint: "" },
        { word: "canada", hint: "" },
        { word: "denmark", hint: "" },
        { word: "egypt", hint: "" },
        { word: "finland", hint: "" },
        { word: "germany", hint: "" },
        { word: "hungary", hint: "" },
        { word: "india", hint: "" },
        { word: "jamaica", hint: "" },
        { word: "kazakhstan", hint: "" },
        { word: "luxembourg", hint: "A small, landlocked country in Europe" },
        { word: "mexico", hint: "" },
        { word: "nepal", hint: "" },
        { word: "oman", hint: "" },
        { word: "portugal", hint: "" },
        { word: "qatar", hint: "" },
        { word: "romania", hint: "" },
        { word: "spain", hint: "" },
        { word: "thailand", hint: "" },
        { word: "uganda", hint: "" },
        { word: "vietnam", hint: "" },
        { word: "wales", hint: "" },
        { word: "yemen", hint: "" },
        { word: "zimbabwe", hint: "" },
        { word: "algeria", hint: "" },
        { word: "belgium", hint: "" },
        { word: "chile", hint: "" },
        { word: "dominican republic", hint: "" },
        { word: "ethiopia", hint: "" },
        { word: "france", hint: "" },
        { word: "greece", hint: "" },
        { word: "haiti", hint: "" },
        { word: "indonesia", hint: "" },
        { word: "japan", hint: "" },
        { word: "kenya", hint: "" },
        { word: "lebanon", hint: "" },
        { word: "malaysia", hint: "" },
        { word: "netherlands", hint: "" },
        { word: "oman", hint: "" },
        { word: "peru", hint: "" },
        { word: "russia", hint: "" },
        { word: "south africa", hint: "" },
        { word: "turkey", hint: "" },
        { word: "ukraine", hint: "" },
        { word: "venezuela", hint: "" },
        { word: "yemen", hint: "" },
        { word: "zambia", hint: "" },
        { word: "australia", hint: "" },
        { word: "bhutan", hint: "" },
        { word: "china", hint: "" },
        { word: "ecuador", hint: "" },
        { word: "fiji", hint: "" },
        { word: "guatemala", hint: "" },
        { word: "iceland", hint: "" },
        { word: "iraq", hint: "" },
        { word: "italy", hint: "" },
        { word: "jordan", hint: "" },
        { word: "kuwait", hint: "" },
        { word: "latvia", hint: "" },
        { word: "madagascar", hint: "An island nation off the southeast coast of Africa" },
        { word: "norway", hint: "" },
        { word: "philippines", hint: "" },
        { word: "saudi arabia", hint: "" },
        { word: "switzerland", hint: "" },
        { word: "tunisia", hint: "" },
        { word: "uruguay", hint: "" },
        { word: "uzbekistan", hint: "" },
        { word: "vanuatu", hint: "A Pacific island nation" },
        { word: "zambia", hint: "" },
        { word: "andorra", hint: "" },
        { word: "botswana", hint: "" },
        { word: "cambodia", hint: "" },
        { word: "djibouti", hint: "" },
        { word: "estonia", hint: "" },
        { word: "georgia", hint: "" },
        { word: "hungary", hint: "" },
        { word: "iran", hint: "" },
        { word: "jordan", hint: "" },
        { word: "kuwait", hint: "" },
        { word: "liechtenstein", hint: "A small, landlocked country in Europe" },
        { word: "malawi", hint: "" },
        { word: "namibia", hint: "" },
        { word: "oman", hint: "" },
        { word: "paraguay", hint: "" },
        { word: "qatar", hint: "" },
        { word: "slovakia", hint: "" },
        { word: "tanzania", hint: "" },
        { word: "uzbekistan", hint: "" },
        { word: "vatican city", hint: "The smallest independent state in the world" },
        { word: "yemen", hint: "" },
        { word: "zambia", hint: "" }
    ],
    "Cities": [
        { word: "amsterdam", hint: "" },
        { word: "bangkok", hint: "" },
        { word: "cairo", hint: "" },
        { word: "delhi", hint: "" },
        { word: "edmonton", hint: "" },
        { word: "florence", hint: "" },
        { word: "geneva", hint: "" },
        { word: "helsinki", hint: "" },
        { word: "istanbul", hint: "" },
        { word: "jakarta", hint: "" },
        { word: "kyoto", hint: "" },
        { word: "lisbon", hint: "" },
        { word: "madrid", hint: "" },
        { word: "nairobi", hint: "" },
        { word: "oslo", hint: "" },
        { word: "paris", hint: "" },
        { word: "quito", hint: "" },
        { word: "rome", hint: "" },
        { word: "seoul", hint: "" },
        { word: "tokyo", hint: "" },
        { word: "ulaanbaatar", hint: "The capital of Mongolia" },
        { word: "vienna", hint: "" },
        { word: "warsaw", hint: "" },
        { word: "xiamen", hint: "A port city on China’s southeast coast" },
        { word: "yokohama", hint: "" },
        { word: "zurich", hint: "" },
        { word: "athens", hint: "" },
        { word: "beijing", hint: "" },
        { word: "copenhagen", hint: "" },
        { word: "dublin", hint: "" },
        { word: "edinburgh", hint: "" },
        { word: "frankfurt", hint: "" },
        { word: "gothenburg", hint: "" },
        { word: "hanoi", hint: "" },
        { word: "istanbul", hint: "" },
        { word: "jerusalem", hint: "" },
        { word: "kiev", hint: "" },
        { word: "london", hint: "" },
        { word: "moscow", hint: "" },
        { word: "new york", hint: "" },
        { word: "osaka", hint: "" },
        { word: "prague", hint: "" },
        { word: "rio de janeiro", hint: "" },
        { word: "singapore", hint: "" },
        { word: "taipei", hint: "" },
        { word: "ulaanbaatar", hint: "The capital of Mongolia" },
        { word: "vancouver", hint: "" },
        { word: "washington", hint: "" },
        { word: "xian", hint: "An ancient city in central China" },
        { word: "yerevan", hint: "The capital of Armenia" },
        { word: "zagreb", hint: "" },
        { word: "abu dhabi", hint: "" },
        { word: "brussels", hint: "" },
        { word: "chicago", hint: "" },
        { word: "dubai", hint: "" },
        { word: "el paso", hint: "" },
        { word: "fukuoka", hint: "" },
        { word: "guangzhou", hint: "" },
        { word: "hamburg", hint: "" },
        { word: "istanbul", hint: "" },
        { word: "johannesburg", hint: "" },
        { word: "kathmandu", hint: "" },
        { word: "los angeles", hint: "" },
        { word: "munich", hint: "" },
        { word: "nashville", hint: "" },
        { word: "ottawa", hint: "" },
        { word: "philadelphia", hint: "" },
        { word: "quebec", hint: "" },
        { word: "rome", hint: "" },
        { word: "sydney", hint: "" },
        { word: "tianjin", hint: "A major port city in northeastern China" },
        { word: "ulsan", hint: "" },
        { word: "vienna", hint: "" },
        { word: "wuhan", hint: "" },
        { word: "xining", hint: "The capital of Qinghai Province, China" },
        { word: "yogyakarta", hint: "A city on the Indonesian island of Java" },
        { word: "zagreb", hint: "" },
        { word: "ankara", hint: "" },
        { word: "berlin", hint: "" },
        { word: "chennai", hint: "" },
        { word: "durban", hint: "" },
        { word: "frankfurt", hint: "" },
        { word: "gaza", hint: "" },
        { word: "hamburg", hint: "" },
        { word: "istanbul", hint: "" },
        { word: "kabul", hint: "" },
        { word: "lima", hint: "" },
        { word: "mexico city", hint: "" },
        { word: "nairobi", hint: "" },
        { word: "oslo", hint: "" },
        { word: "quito", hint: "" },
        { word: "riyadh", hint: "" },
        { word: "sofia", hint: "" },
        { word: "tashkent", hint: "" },
        { word: "ulsan", hint: "" },
        { word: "vienna", hint: "" },
        { word: "wroclaw", hint: "" },
        { word: "xiamen", hint: "A port city on China’s southeast coast" },
        { word: "yerevan", hint: "The capital of Armenia" },
        { word: "zagreb", hint: "" }
    ],
    "Colors": [
        { word: "red", hint: "" },
        { word: "blue", hint: "" },
        { word: "green", hint: "" },
        { word: "yellow", hint: "" },
        { word: "purple", hint: "" },
        { word: "orange", hint: "" },
        { word: "pink", hint: "" },
        { word: "brown", hint: "" },
        { word: "black", hint: "" },
        { word: "white", hint: "" },
        { word: "amber", hint: "" },
        { word: "aquamarine", hint: "" },
        { word: "azure", hint: "" },
        { word: "beige", hint: "" },
        { word: "cerulean", hint: "A shade of blue" },
        { word: "charcoal", hint: "" },
        { word: "coral", hint: "" },
        { word: "crimson", hint: "" },
        { word: "cyan", hint: "" },
        { word: "fuchsia", hint: "" },
        { word: "gold", hint: "" },
        { word: "indigo", hint: "" },
        { word: "ivory", hint: "" },
        { word: "jade", hint: "" },
        { word: "lavender", hint: "" },
        { word: "lime", hint: "" },
        { word: "magenta", hint: "" },
        { word: "maroon", hint: "" },
        { word: "mint", hint: "" },
        { word: "navy", hint: "" },
        { word: "olive", hint: "" },
        { word: "peach", hint: "" },
        { word: "periwinkle", hint: "" },
        { word: "plum", hint: "" },
        { word: "rose", hint: "" },
        { word: "ruby", hint: "" },
        { word: "salmon", hint: "" },
        { word: "sapphire", hint: "" },
        { word: "scarlet", hint: "" },
        { word: "silver", hint: "" },
        { word: "teal", hint: "" },
        { word: "turquoise", hint: "" },
        { word: "violet", hint: "" },
        { word: "wine", hint: "" },
        { word: "alabaster", hint: "" },
        { word: "blush", hint: "" },
        { word: "bronze", hint: "" },
        { word: "chartreuse", hint: "A shade of green with a hint of yellow" },
        { word: "emerald", hint: "" },
        { word: "graphite", hint: "" },
        { word: "lemon chiffon", hint: "" },
        { word: "mustard", hint: "" },
        { word: "peacock", hint: "" },
        { word: "sepia", hint: "" },
        { word: "taupe", hint: "A dark brown-gray color" },
        { word: "umber", hint: "" },
        { word: "vermillion", hint: "A brilliant red or scarlet" },
        { word: "wisteria", hint: "A light violet color" },
        { word: "zinnwaldite", hint: "A yellow-brown color" },
        { word: "ash", hint: "" },
        { word: "bittersweet", hint: "" },
        { word: "bistre", hint: "" },
        { word: "carmine", hint: "" },
        { word: "ecru", hint: "" },
        { word: "eggplant", hint: "" },
        { word: "flame", hint: "" },
        { word: "folly", hint: "" },
        { word: "gainsboro", hint: "A muted and desaturated gray color" },
        { word: "heliotrope", hint: "A pink-purple tint" },
        { word: "khaki", hint: "" },
        { word: "lilac", hint: "" },
        { word: "mauve", hint: "" },
        { word: "orchid", hint: "" },
        { word: "pear", hint: "" },
        { word: "quartz", hint: "" },
        { word: "rainbow", hint: "" },
        { word: "ruby", hint: "" },
        { word: "smoky black", hint: "" },
        { word: "tan", hint: "" },
        { word: "verdigris", hint: "" },
        { word: "xanthic", hint: "" },
        { word: "zaffre", hint: "A deep blue color" },
        { word: "zomp", hint: "" },
        { word: "alizarin", hint: "" },
        { word: "amaranth", hint: "" },
        { word: "antique brass", hint: "" },
        { word: "barn red", hint: "" },
        { word: "cadet blue", hint: "" },
        { word: "davys grey", hint: "" },
        { word: "egyptian blue", hint: "" }
    ],
    "Vegetables": [
        { word: "carrot", hint: "" },
        { word: "broccoli", hint: "" },
        { word: "cauliflower", hint: "" },
        { word: "spinach", hint: "" },
        { word: "kale", hint: "" },
        { word: "cabbage", hint: "" },
        { word: "lettuce", hint: "" },
        { word: "peas", hint: "" },
        { word: "beetroot", hint: "" },
        { word: "potato", hint: "" },
        { word: "artichoke", hint: "" },
        { word: "asparagus", hint: "" },
        { word: "beans", hint: "" },
        { word: "bell pepper", hint: "" },
        { word: "brussels sprouts", hint: "" },
        { word: "butternut squash", hint: "" },
        { word: "chard", hint: "" },
        { word: "collard greens", hint: "" },
        { word: "corn", hint: "" },
        { word: "cucumber", hint: "" },
        { word: "eggplant", hint: "" },
        { word: "fennel", hint: "" },
        { word: "garlic", hint: "" },
        { word: "ginger", hint: "" },
        { word: "horseradish", hint: "" },
        { word: "jicama", hint: "" },
        { word: "kohlrabi", hint: "A type of cabbage" },
        { word: "leek", hint: "" },
        { word: "mushroom", hint: "" },
        { word: "okra", hint: "" },
        { word: "onion", hint: "" },
        { word: "parsnip", hint: "" },
        { word: "pumpkin", hint: "" },
        { word: "radish", hint: "" },
        { word: "rutabaga", hint: "A root vegetable similar to a turnip" },
        { word: "shallot", hint: "" },
        { word: "snow pea", hint: "" },
        { word: "sweet potato", hint: "" },
        { word: "tomato", hint: "" },
        { word: "turnip", hint: "" },
        { word: "watercress", hint: "" },
        { word: "yam", hint: "" },
        { word: "zucchini", hint: "" },
        { word: "bamboo shoots", hint: "" },
        { word: "bitter melon", hint: "" },
        { word: "bok choy", hint: "" },
        { word: "celery", hint: "" },
        { word: "chayote", hint: "" },
        { word: "cilantro", hint: "" },
        { word: "dandelion greens", hint: "" },
        { word: "edamame", hint: "" },
        { word: "endive", hint: "" },
        { word: "escarole", hint: "" },
        { word: "frisee", hint: "" },
        { word: "jerusalem artichoke", hint: "" },
        { word: "lemongrass", hint: "" },
        { word: "lotus root", hint: "" },
        { word: "mung bean", hint: "" },
        { word: "mustard greens", hint: "" },
        { word: "nopales", hint: "" },
        { word: "radicchio", hint: "" },
        { word: "romaine", hint: "" },
        { word: "scallion", hint: "" },
        { word: "seaweed", hint: "" },
        { word: "sprouts", hint: "" },
        { word: "squash", hint: "" },
        { word: "sunchoke", hint: "Also known as Jerusalem artichoke" },
        { word: "taro", hint: "" },
        { word: "water chestnut", hint: "" },
        { word: "winter squash", hint: "" },
        { word: "broad beans", hint: "" },
        { word: "chicory", hint: "" },
        { word: "daikon", hint: "" },
        { word: "fiddlehead", hint: "" },
        { word: "florence fennel", hint: "" },
        { word: "garden cress", hint: "" },
        { word: "gobo", hint: "A root vegetable also known as burdock root" },
        { word: "hyacinth bean", hint: "" },
        { word: "mizuna", hint: "" },
        { word: "purslane", hint: "" },
        { word: "samphire", hint: "A sea vegetable also known as sea asparagus" },
        { word: "seakale", hint: "" },
        { word: "sorrel", hint: "" },
        { word: "tatsoi", hint: "" },
        { word: "tindora", hint: "" },
        { word: "tok choy", hint: "" },
        { word: "tuscan kale", hint: "" },
        { word: "welsh onion", hint: "" },
        { word: "yardlong bean", hint: "" },
        { word: "yuca", hint: "Also known as cassava" }
    ],
    "Movies": [
        { word: "inception", hint: "" },
        { word: "avatar", hint: "" },
        { word: "gladiator", hint: "" },
        { word: "titanic", hint: "" },
        { word: "braveheart", hint: "" },
        { word: "jaws", hint: "" },
        { word: "rocky", hint: "" },
        { word: "matrix", hint: "" },
        { word: "fargo", hint: "" },
        { word: "goodfellas", hint: "" },
        { word: "aliens", hint: "" },
        { word: "amadeus", hint: "" },
        { word: "brave", hint: "" },
        { word: "casablanca", hint: "" },
        { word: "deadpool", hint: "" },
        { word: "x-men", hint: "" },
        { word: "django", hint: "" },
        { word: "eternals", hint: "" },
        { word: "fury", hint: "" },
        { word: "godfather", hint: "" },
        { word: "halloween", hint: "" },
        { word: "interstellar", hint: "" },
        { word: "joker", hint: "" },
        { word: "killbill", hint: "" },
        { word: "la la land", hint: "" },
        { word: "mad max", hint: "" },
        { word: "no country for old men", hint: "" },
        { word: "oceans 11", hint: "" },
        { word: "predator", hint: "" },
        { word: "quarantine", hint: "" },
        { word: "requiem for a dream", hint: "" },
        { word: "schindler's list", hint: "" },
        { word: "taxi driver", hint: "" },
        { word: "unforgiven", hint: "" },
        { word: "v for vendetta", hint: "" },
        { word: "whiplash", hint: "" },
        { word: "x-men", hint: "" },
        { word: "yesterday", hint: "" },
        { word: "zodiac", hint: "" },
        { word: "apollo 13", hint: "" },
        { word: "batman", hint: "" },
        { word: "creed", hint: "" },
        { word: "dunkirk", hint: "" },
        { word: "evangelion", hint: "" },
        { word: "fight club", hint: "" },
        { word: "gravity", hint: "" },
        { word: "her", hint: "" },
        { word: "incredibles", hint: "" },
        { word: "jackie", hint: "" },
        { word: "kingsman", hint: "" },
        { word: "logan", hint: "" },
        { word: "memento", hint: "" },
        { word: "notting hill", hint: "" },
        { word: "oblivion", hint: "" },
        { word: "patriot", hint: "" },
        { word: "queen", hint: "" },
        { word: "thor", hint: "" },
        { word: "us", hint: "" },
        { word: "venom", hint: "" },
        { word: "warrior", hint: "" },
        { word: "xanadu", hint: "" },
        { word: "year one", hint: "" },
        { word: "zoolander", hint: "" },
        { word: "avatar 2", hint: "" },
        { word: "black panther", hint: "" },
        { word: "coco", hint: "" },
        { word: "dark knight", hint: "" },
        { word: "et", hint: "" },
        { word: "finding nemo", hint: "" },
        { word: "gattaca", hint: "" },
        { word: "hotel rwanda", hint: "" },
        { word: "in bruges", hint: "" },
        { word: "john wick", hint: "" },
        { word: "kung fu panda", hint: "" },
        { word: "life of pi", hint: "" },
        { word: "moonlight", hint: "" },
        { word: "nightcrawler", hint: "" },
        { word: "oldboy", hint: "" },
        { word: "parasite", hint: "" }
    ],
    "Sports": [
        { word: "soccer", hint: "" },
        { word: "basketball", hint: "" },
        { word: "baseball", hint: "" },
        { word: "tennis", hint: "" },
        { word: "cricket", hint: "" },
        { word: "golf", hint: "" },
        { word: "rugby", hint: "" },
        { word: "hockey", hint: "" },
        { word: "swimming", hint: "" },
        { word: "cycling", hint: "" },
        { word: "badminton", hint: "" },
        { word: "boxing", hint: "" },
        { word: "curling", hint: "" },
        { word: "diving", hint: "" },
        { word: "equestrian", hint: "" },
        { word: "fencing", hint: "" },
        { word: "gymnastics", hint: "" },
        { word: "handball", hint: "" },
        { word: "ice skating", hint: "" },
        { word: "judo", hint: "" },
        { word: "karate", hint: "" },
        { word: "lacrosse", hint: "" },
        { word: "martial arts", hint: "" },
        { word: "netball", hint: "" },
        { word: "orienteering", hint: "" },
        { word: "polo", hint: "" },
        { word: "quidditch", hint: "" },
        { word: "rowing", hint: "" },
        { word: "skiing", hint: "" },
        { word: "table tennis", hint: "" },
        { word: "ultimate frisbee", hint: "" },
        { word: "volleyball", hint: "" },
        { word: "weightlifting", hint: "" },
        { word: "x games", hint: "" },
        { word: "yachting", hint: "" },
        { word: "zumba", hint: "" },
        { word: "archery", hint: "" },
        { word: "billiards", hint: "" },
        { word: "canoeing", hint: "" },
        { word: "darts", hint: "" },
        { word: "esports", hint: "" },
        { word: "freerunning", hint: "" },
        { word: "gaelic football", hint: "" },
        { word: "hang gliding", hint: "" },
        { word: "ice hockey", hint: "" },
        { word: "jai alai", hint: "" },
        { word: "kayaking", hint: "" },
        { word: "luge", hint: "" },
        { word: "motorsport", hint: "" },
        { word: "nordic walking", hint: "" },
        { word: "parkour", hint: "" },
        { word: "quad biking", hint: "" },
        { word: "roller derby", hint: "" },
        { word: "snowboarding", hint: "" },
        { word: "taekwondo", hint: "" },
        { word: "underwater hockey", hint: "" },
        { word: "vaulting", hint: "" },
        { word: "water polo", hint: "" },
        { word: "xtreme sports", hint: "" },
        { word: "yoga", hint: "" },
        { word: "zorb football", hint: "" },
        { word: "aikido", hint: "" },
        { word: "base jumping", hint: "" },
        { word: "cheerleading", hint: "" },
        { word: "discus throw", hint: "" },
        { word: "endurance racing", hint: "" },
        { word: "futsal", hint: "" },
        { word: "greyhound racing", hint: "" },
        { word: "hurling", hint: "" },
        { word: "indoor soccer", hint: "" },
        { word: "jujitsu", hint: "" },
        { word: "kickboxing", hint: "" },
        { word: "land sailing", hint: "" },
        { word: "muay thai", hint: "" },
        { word: "paintball", hint: "" },
        { word: "road racing", hint: "" },
        { word: "softball", hint: "" },
        { word: "trampolining", hint: "" }
    ],
    "Brands": [
        { word: "nike", hint: "" },
        { word: "adidas", hint: "" },
        { word: "apple", hint: "" },
        { word: "samsung", hint: "" },
        { word: "sony", hint: "" },
        { word: "tesla", hint: "" },
        { word: "microsoft", hint: "" },
        { word: "google", hint: "" },
        { word: "amazon", hint: "" },
        { word: "facebook", hint: "" },
        { word: "bmw", hint: "" },
        { word: "coca cola", hint: "" },
        { word: "disney", hint: "" },
        { word: "ford", hint: "" },
        { word: "general electric", hint: "" },
        { word: "honda", hint: "" },
        { word: "ibm", hint: "" },
        { word: "intel", hint: "" },
        { word: "johnson & johnson", hint: "Healthcare and pharmaceutical" },
        { word: "kfc", hint: "" },
        { word: "lg", hint: "" },
        { word: "louis vuitton", hint: "Luxury fashion brand" },
        { word: "mastercard", hint: "" },
        { word: "mcdonalds", hint: "" },
        { word: "mercedes-benz", hint: "German car maufacturer" },
        { word: "nestle", hint: "" },
        { word: "nissan", hint: "" },
        { word: "pepsi", hint: "" },
        { word: "philips", hint: "" },
        { word: "porsche", hint: "" },
        { word: "red bull", hint: "" },
        { word: "santander", hint: "A multinational bank" },
        { word: "shell", hint: "" },
        { word: "starbucks", hint: "" },
        { word: "toyota", hint: "" },
        { word: "visa", hint: "" },
        { word: "volkswagen", hint: "" },
        { word: "walmart", hint: "" },
        { word: "whirlpool", hint: "" },
        { word: "xbox", hint: "" },
        { word: "yahoo", hint: "" },
        { word: "zara", hint: "" },
        { word: "acer", hint: "" },
        { word: "airbnb", hint: "" },
        { word: "audi", hint: "" },
        { word: "avon", hint: "" },
        { word: "baidu", hint: "A Chinese search engine" },
        { word: "boeing", hint: "" },
        { word: "burberry", hint: "" },
        { word: "cadillac", hint: "" },
        { word: "canon", hint: "" },
        { word: "chanel", hint: "" },
        { word: "chevrolet", hint: "" },
        { word: "dell", hint: "" },
        { word: "dior", hint: "" },
        { word: "domino's", hint: "" },
        { word: "durex", hint: "" },
        { word: "ebay", hint: "" },
        { word: "exxon", hint: "" },
        { word: "fedex", hint: "" },
        { word: "ferrari", hint: "" },
        { word: "fujitsu", hint: "" },
        { word: "gopro", hint: "" },
        { word: "gucci", hint: "" },
        { word: "harley davidson", hint: "" },
        { word: "heineken", hint: "" },
        { word: "hermes", hint: "" },
        { word: "hp", hint: "" },
        { word: "hyundai", hint: "" },
        { word: "ikea", hint: "" },
        { word: "jaguar", hint: "" },
        { word: "jbl", hint: "" },
        { word: "john deere", hint: "Agricultural machinery" },
        { word: "kellogg's", hint: "" },
        { word: "kodak", hint: "" },
        { word: "lego", hint: "" },
        { word: "levi's", hint: "" },
        { word: "lexus", hint: "" },
        { word: "lucasfilm", hint: "Film production company" },
        { word: "marlboro", hint: "" },
        { word: "michelin", hint: "" },
        { word: "moet", hint: "" },
        { word: "nivea", hint: "" },
        { word: "oracle", hint: "" },
        { word: "pampers", hint: "" },
        { word: "paypal", hint: "" },
        { word: "prada", hint: "" },
        { word: "reebok", hint: "" },
        { word: "rolex", hint: "" }
    ]
}
